apiVersion: apps/v1 
kind: Deployment
metadata:
  name: my-app-deployment 
  labels: 
    app: Deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-pod
  template:
    metadata:
      labels:
        app: deployment-pod
    spec:
      containers:
      - name: container
        image: rajrishab/challenge2:1.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"
            memory: "64Mi"
          limits:
            cpu: "400m"
            memory: "128Mi"
        readinessProbe: # Readiness probe
          httpGet:
            path: /health/
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
        livenessProbe: # Liveness probe
          httpGet:
            path: /health/
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: service
spec:
  type: NodePort 
  selector:
    app: deployment-pod
  ports:
    - protocol: TCP
      name: http-port
      port: 80
      targetPort: 80 
      nodePort: 30080