apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runner-deployments
rules:
- apiGroups: ["apps",""]
  resources:
  - deployments
  verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: runner-deployments-binding
subjects:
- kind: ServiceAccount
  name: runner-sa
  namespace: actions-runner-system
roleRef:
  kind: ClusterRole
  name: runner-deployments
  apiGroup: rbac.authorization.k8s.io