apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: kubernetes-runner
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: runner-sa # This ServiceAccount needs permissions
      repository: Rishab49/DevOps-Challenges # Update to your target repo (e.g., siddhant-khisty/key-store-gin)
      labels:
        - "kubernetes-runner" # Label to target this runner in your workflow